export const TEXTS = {
  NAME: "Gurjung.Singh",
  INTRO_DESC1: "Hey, I'm Frontend Developer",
  INTRO_DESC2: "Building beautiful web experiences",
  WORK: "My Recent Work",
  TECHSTACK: "Tech I Use",
  URIS: {
    HOME: "HOME",
    TECH: "Tech I Use",
    PROJECTS: "My Work",
    CONTACT: "Hire Me",
  },
  VIEW_WORK: "View my work",
  VIEW_CV: "My CV",
  TECH: {
    HTML: "HTML",
    CSS: "CSS",
    JS: "Javascript",
    REACT: "React",
    REDUX: "Redux",
    MUI: "Material UI",
    ANT_DESIGN: "Ant Design",
    SASS: "SASS",
    TAILWIND_CSS: "Tailwind CSS",
    CHART_JS: "Chart.js",
    LEAFLET: "React Leaflet",
  },
  PROJECTS: {
    ONE: "Notes",
    TWO: "Covid19 Tracker",
  },
  FORM: {
    NAME: "Name",
    EMAIL: "Email",
    SUBMIT: "Send It!",
    SUBJECT: "Subject",
    MESSAGE: "Message",
    CONFIRMATION: "Thank you contacting me...",
  },
  FOOTER_DESC: "Let's keep in touch and work together",
};
